name       : moreutils
version    : 0.63
release    : 2
source     :
    - git|git://git.kitenet.net/moreutils.git : 0.63
license    : GPL-2.0-or-later
component  : system.utils
summary    : additional Unix utilities
description: |
    This is a growing collection of the Unix tools that nobody thought to write long ago, when Unix was young.
builddeps  :
    - docbook-xml
setup      : |
    # patch to change docbook directory and remove conflicting man page
    %patch < $pkgfiles/Makefile.patch
build      : |
    %make
install    : |
    %make_install
